name: Add ETF Tickers

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  add_ticker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pandas requests beautifulsoup4 lxml

      - name: Run ticker enrichment
        run: python scripts/add_ticker_to_csv.py

      - name: Commit updated CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if [ -n "$(git status --porcelain 'ETF_list prova v1.csv')" ]; then
            git add 'ETF_list prova v1.csv'
            git commit -m "Aggiornato ETF_list prova v1.csv con colonna Ticker"
            git push
          fi
