name: Fetch ETF UCITS List

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1" # ogni lunedì alle 5:00 CET

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run JustETF fetcher
        run: python scripts/fetch_etf_list.py

      - name: Commit updated list
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if [ -n "$(git status --porcelain ETF_list.csv)" ]; then
            git add ETF_list.csv
            git commit -m "Auto-update ETF UCITS list from JustETF API"
            git push
          fi
