name: Map ISIN to Ticker

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  map:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas requests beautifulsoup4 lxml

      - name: Run ISIN→Ticker mapper
        run: python scripts/map_isin_to_ticker.py

      - name: Commit updated CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if [ -n "$(git status --porcelain ETF_list_con_ticker.csv)" ]; then
            git add ETF_list_con_ticker.csv
            git commit -m "Aggiornato mapping ISIN→Ticker (preferenza Borsa Italiana)"
            git push
          fi
